---

- name: Configuring timezone
  template: >
    src=etc-timezone.j2
    dest=/etc/timezone
    owner=root
    group=root
    mode=0644
  notify: reconfigure tzdata
  tags:
    - system
    - timezone
    - config