---
# For more information about handlers see:
# http://www.ansibleworks.com/docs/playbooks.html#handlers-running-operations-on-change

- name: reconfigure tzdata
  shell: dpkg-reconfigure -f noninteractive tzdata